### ISSUE TITLE
the checker didn't open with me !

### ISSUE THREAD

**Issue by fathyme** [BitTheByte/GmailChecker#1]
the checker didn't open with me !

**Comment by BitTheByte** [comment]
Please describe your issue more in detail

**Comment by ahmedtroy** [comment]
كل مشغلو يطلع نفس الجميلات  بيطلع عدد ويوقف 
ولما ابص علي التكست بلاقي الجميلات شبة بعض

**Comment by BitTheByte** [comment]
Closed for inactivity
